services:
  catalogdb:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6000:8080"
    depends_on:
      - catalogdb